const FETCH_REQUEST = 'users/FETCH_REQUEST';
const FETCH_SUCCESS = 'users/FETCH_SUCCESS';
const FETCH_ERROR = 'users/FETCH_ERROR';
const TOGGLE_PREVIOUS_PAGE = 'pagination/TOGGLE_PREVIOUS_PAGE';
const TOGGLE_NEXT_PAGE = 'pagination/TOGGLE_NEXT_PAGE';

export default {
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,

  TOGGLE_PREVIOUS_PAGE,
  TOGGLE_NEXT_PAGE,
};
